print("i wake up at 6")
print("then I brush my teeth and take a bath")
print("after that I eat breakfast")
print("then I pack up and get ready for school")
print("I arrive at school")
print("after I finish school and come home,I play games")
print("after 1 hour,I study for 1.5 hours")
print("then i have dinner and go to bed")
print("1.5*7=",1.5*7)